remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "contrast"
title: "Galia Appel's Website"
title_separator: "-"
name: "Galia Appel"

atom_feed:
  hide: true

plugins:
  - jekyll-include-cache
  - jemoji

author:
  name: "Galia Appel"
  avatar: "/assets/images/profile.png"
  bio: "\"In God we trust. All others must bring data.\" — W. Edwards Deming"
  location: Rehovot, Israel
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Galia-A"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/galiaappel/"
